import {ProductInterface} from '../../types/models/product-interface'

export const productsWardrobes: ProductInterface[] = [
    {
        id: 74,
        categoryId: 1,
        article: 'L-0',
        translit: '',
        name: 'Фараон (вешалка)',
        cost: 16900,
        description: null,
        creationDate: '2020-04-25',
    },
    {
        id: 75,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Фараон (вешалка+полки)',
        cost: 20200,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 76,
        categoryId: 1,
        article: 'L-2',
        translit: '',
        name: 'Фараон (3-х)',
        cost: 24200,
        description: 'Описание Кровать два',
        creationDate: '2020-04-25',
    },
    {
        id: 77,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Фараон (4-х)',
        cost: 31500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 78,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Классика (вешалка)',
        cost: 16500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 79,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Классика (вешалка + полки)',
        cost: 19600,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 80,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Классика (3-х)',
        cost: 22800,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 81,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Классика (4-х)',
        cost: 30500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 82,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Шкаф-купе (вешалка)',
        cost: 17500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 83,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Шкаф-купе (вешалка + полки)',
        cost: 20600,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 84,
        categoryId: 1,
        article: 'L-0',
        translit: '',
        name: 'Шкаф-купе (3-х)',
        cost: 23800,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 85,
        categoryId: 1,
        article: 'L-1',
        translit: '',
        name: 'Шкаф-купе (4-х)',
        cost: 31500,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 86,
        categoryId: 1,
        article: 'L-2',
        translit: '',
        name: 'Афина (вешалка + полки)',
        cost: 18300,
        description: 'Описание Кровать два',
        creationDate: '2020-04-01',
    },
]
