import {ProductInterface} from '../../types/models/product-interface'

export const productsTables: ProductInterface[] = [
    {
        id: 32,
        categoryId: 8,
        article: 'L-0',
        translit: '',
        name: 'Стол-парта',
        cost: 5400,
        description: 'Описание Кровать Афина',
        creationDate: '2020-04-25',
    },
    {
        id: 33,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол-парта (с рамкой)',
        cost: 5700,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 34,
        categoryId: 8,
        article: 'L-2',
        translit: '',
        name: 'Стол В1',
        cost: 5700,
        description: 'Описание Кровать два',
        creationDate: '2020-04-25',
    },
    {
        id: 35,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол В2',
        cost: 6300,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 36,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол В4',
        cost: 6300,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 37,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол №1',
        cost: 5900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 38,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол №2',
        cost: 6300,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 39,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол №3',
        cost: 5900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 40,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол-паук',
        cost: 6200,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 41,
        categoryId: 8,
        article: 'L-1',
        translit: '',
        name: 'Стол-паук',
        cost: 6800,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 42,
        categoryId: 8,
        article: 'L-0',
        translit: '',
        name: 'Стол дачный',
        cost: 5900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 43,
        categoryId: 7,
        article: 'L-1',
        translit: '',
        name: 'Стол журнальный однобалясный',
        cost: 4300,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 44,
        categoryId: 7,
        article: 'L-2',
        translit: '',
        name: 'Стол журнальный 2-х балясный',
        cost: 4700,
        description: 'Описание Кровать два',
        creationDate: '2020-04-01',
    },
    {
        id: 45,
        categoryId: 7,
        article: 'L-1',
        translit: '',
        name: 'Стол журнальный слоник',
        cost: 4800,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 46,
        categoryId: 7,
        article: 'L-1',
        translit: '',
        name: 'Стол журнальный Ж4',
        cost: 4500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
]

// todo - Сделать проверку на уникальный id
