import {ProductInterface} from '../../types/models/product-interface'

export const productsChairs: ProductInterface[] = [
    {
        id: 65,
        categoryId: 4,
        article: 'L-0',
        translit: '',
        name: 'ГРАНД',
        cost: 2100,
        description: 'Описание Кровать Афина',
        creationDate: '2020-04-25',
    },
    {
        id: 47,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Стул точеный', // todo - добавить свойство жесткий/мягкий
        cost: 2000,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 48,
        categoryId: 4,
        article: 'L-2',
        translit: '',
        name: 'Лорд',
        cost: 2100,
        description: 'Описание Кровать два',
        creationDate: '2020-04-25',
    },
    {
        id: 64,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Дачный',
        cost: 2100,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 49,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Миша',
        cost: 2000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 50,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Ваня',
        cost: 2100,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 51,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Фортуна',
        cost: 2900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 52,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Банкетка',
        cost: 1350,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 53,
        categoryId: 10,
        article: 'L-1',
        translit: '',
        name: 'Табурет точеный',
        cost: 1000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 54,
        categoryId: 10,
        article: 'L-1',
        translit: '',
        name: 'Новый',
        cost: 900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 55,
        categoryId: 10,
        article: 'L-0',
        translit: '',
        name: 'Табурет дачный',
        cost: 900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 56,
        categoryId: 10,
        article: 'L-1',
        translit: '',
        name: 'Квадра',
        cost: 900,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 57,
        categoryId: 4,
        article: 'L-2',
        translit: '',
        name: 'Лавка банная',
        cost: 2500,
        description: 'Описание Кровать два',
        creationDate: '2020-04-01',
    },
    {
        id: 58,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Лавка',
        cost: 2500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 59,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Диван дачный на базе стула',
        cost: 6000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 60,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Диван дачный Адино',
        cost: 6000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 61,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Скамья с подлокотниками',
        cost: 5500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 62,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Кресло Адино большое',
        cost: 3500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 63,
        categoryId: 4,
        article: 'L-1',
        translit: '',
        name: 'Кресло Адино малое',
        cost: 3000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
]
