import {ProductInterface} from '../../types/models/product-interface'

export const productsBeds: ProductInterface[] = [
    /*
        Кровати для подкатегории: 0
     */
    {
        id: 0,
        categoryId: 0,
        article: 'L-0',
        translit: '',
        name: 'Афина',
        cost: 6000,
        description: 'Описание Кровать Афина',
        creationDate: '2020-04-25',
    },
    {
        id: 1,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Афродита',
        cost: 6000,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 2,
        categoryId: 5,
        article: 'L-2',
        translit: '',
        name: 'Гармония',
        cost: 9200,
        description: 'Описание Кровать два',
        creationDate: '2020-04-25',
    },
    {
        id: 3,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Гера',
        cost: 5900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 4,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Дачная (простая)',
        cost: 4550,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 5,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Дачная (точеная)',
        cost: 4750,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 6,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Джулия',
        cost: 5750,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 7,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Диана',
        cost: 5550,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 8,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Классика',
        cost: 5950,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 9,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Лагуна',
        cost: 5150,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 10,
        categoryId: 0,
        article: 'L-0',
        translit: '',
        name: 'Лама',
        cost: 5800,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 11,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Лира',
        cost: 6300,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 12,
        categoryId: 0,
        article: 'L-2',
        translit: '',
        name: 'Машенька',
        cost: 4950,
        description: 'Описание Кровать два',
        creationDate: '2020-04-01',
    },
    {
        id: 13,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Муза',
        cost: 5900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 14,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Нефертити',
        cost: 6050,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 15,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Нова',
        cost: 5750,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 16,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Сакура',
        cost: 5250,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 17,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Сатори',
        cost: 5900,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 18,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Соната',
        cost: 6000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 19,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Сонька',
        cost: 5500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 20,
        categoryId: 0,
        article: 'L-0',
        translit: '',
        name: 'Соня',
        cost: 5350,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 21,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Стиль',
        cost: 7600,
        description: 'Описание Кровать один',
        creationDate: '2020-04-01',
    },
    {
        id: 22,
        categoryId: 0,
        article: 'L-2',
        translit: '',
        name: 'Фараон',
        cost: 8900,
        description: 'Описание Кровать два',
        creationDate: '2020-04-01',
    },
    {
        id: 23,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Филенка',
        cost: 6000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 24,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Элита',
        cost: 7100,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 25,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Элита (кар стяжка)',
        cost: 12700,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 26,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Юката',
        cost: 6300,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 27,
        categoryId: 0,
        article: 'L-1',
        translit: '',
        name: 'Виола (ковка+кар стяжка)',
        cost: 19550,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 28,
        categoryId: 9,
        article: 'L-1',
        translit: '',
        name: 'Дачная 2',
        cost: 8200,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 29,
        categoryId: 9,
        article: 'L-1',
        translit: '',
        name: 'Маша 2',
        cost: 9100,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 30,
        categoryId: 9,
        article: 'L-1',
        translit: '',
        name: 'Соня 2',
        cost: 9700,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
    {
        id: 31,
        categoryId: 9,
        article: 'L-1',
        translit: '',
        name: 'Чердак',
        cost: 8800,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-01',
    },
]

// todo - Сделать проверку на уникальный id
