import {ProductInterface} from '../../types/models/product-interface'

export const productsBedsideTables: ProductInterface[] = [
    {
        id: 66,
        categoryId: 2,
        article: 'L-0',
        translit: '',
        name: 'Классика',
        cost: 6600,
        description: 'Описание Кровать Афина',
        creationDate: '2020-04-25',
    },
    {
        id: 68,
        categoryId: 11,
        article: 'L-2',
        translit: '',
        name: 'Тумба для обуви малая',
        cost: 4500,
        description: 'Описание Кровать два',
        creationDate: '2020-04-25',
    },
    {
        id: 69,
        categoryId: 11,
        article: 'L-1',
        translit: '',
        name: 'Тумба для обуви большая',
        cost: 8500,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 70,
        categoryId: 11,
        article: 'L-1',
        translit: '',
        name: 'Обувница',
        cost: 4000,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 71,
        categoryId: 2,
        article: 'L-1',
        translit: '',
        name: 'Пенальный столик',
        cost: 8400,
        description: 'Описание Кровать ноль',
        creationDate: '2020-04-25',
    },
    {
        id: 72,
        categoryId: 2,
        article: 'L-1',
        translit: '',
        name: 'Престиж',
        cost: 7000,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
    {
        id: 73,
        categoryId: 2,
        article: 'L-1',
        translit: '',
        name: 'Телефонка',
        cost: 5300,
        description: 'Описание Кровать один',
        creationDate: '2020-04-25',
    },
]
