import ColorInterface from '../types/models/color-interface'

const colors: ColorInterface[] = [
    {
        id: '1',
        colorCategoryId: '2',
        name: 'Зелёно-бежевый',
        ral: 'RAL 1000',
        color: '#CCC58F',
    },
    {
        id: '2',
        colorCategoryId: '2',
        name: 'Бежевый',
        ral: 'RAL 1001',
        color: '#D1BC8A',
    },
    {
        id: '3',
        colorCategoryId: '2',
        name: 'Песочно-жёлтый',
        ral: 'RAL 1002',
        color: '#D2B773',
    },
    {
        id: '4',
        colorCategoryId: '2',
        name: 'Сигнальный жёлтый',
        ral: 'RAL 1003',
        color: '#F7BA0B',
    },
    {
        id: '5',
        colorCategoryId: '2',
        name: 'Жёлто-золотой',
        ral: 'RAL 1004',
        color: '#E2B007',
    },
    {
        id: '6',
        colorCategoryId: '2',
        name: 'Медово-жёлтый',
        ral: 'RAL 1005',
        color: '#C89F04',
    },
    {
        id: '7',
        colorCategoryId: '2',
        name: 'Кукурузно-жёлтый',
        ral: 'RAL 1006',
        color: '#E1A100',
    },
    {
        id: '8',
        colorCategoryId: '2',
        name: 'Нарциссово-жёлтый',
        ral: 'RAL 1007',
        color: '#E79C00',
    },
    {
        id: '9',
        colorCategoryId: '2',
        name: 'Коричнево-бежевый',
        ral: 'RAL 1011',
        color: '#AF8A54',
    },
    {
        id: '10',
        colorCategoryId: '2',
        name: 'Лимонно-жёлтый',
        ral: 'RAL 1012',
        color: '#D9C022',
    },
    {
        id: '11',
        colorCategoryId: '2',
        name: 'Жемчужно-белый',
        ral: 'RAL 1013',
        color: '#E9E5CE',
    },
    {
        id: '12',
        colorCategoryId: '2',
        name: 'Слоновая кость',
        ral: 'RAL 1014',
        color: '#DED09F',
    },
    {
        id: '13',
        colorCategoryId: '2',
        name: 'Светлая слоновая кость',
        ral: 'RAL 1015',
        color: '#EADEBD',
    },
    {
        id: '14',
        colorCategoryId: '2',
        name: 'Жёлтая сера',
        ral: 'RAL 1016',
        color: '#EAF044',
    },
    {
        id: '15',
        colorCategoryId: '2',
        name: 'Шафраново-жёлтый',
        ral: 'RAL 1017',
        color: '#F4B752',
    },
    {
        id: '16',
        colorCategoryId: '2',
        name: 'Цинково-жёлтый',
        ral: 'RAL 1018',
        color: '#F3E03B',
    },
    {
        id: '17',
        colorCategoryId: '2',
        name: 'Серо-бежевый',
        ral: 'RAL 1019',
        color: '#A4957D',
    },
    {
        id: '18',
        colorCategoryId: '2',
        name: 'Оливково-жёлтый',
        ral: 'RAL 1020',
        color: '#9A9464',
    },
    {
        id: '19',
        colorCategoryId: '2',
        name: 'Рапсово-жёлтый',
        ral: 'RAL 1021',
        color: '#EEC900',
    },
    {
        id: '20',
        colorCategoryId: '2',
        name: 'Транспортно-жёлтый',
        ral: 'RAL 1023',
        color: '#F0CA00',
    },
    {
        id: '21',
        colorCategoryId: '2',
        name: 'Охра жёлтая',
        ral: 'RAL 1024',
        color: '#B89C50',
    },
    {
        id: '23',
        colorCategoryId: '2',
        name: 'Карри жёлтый',
        ral: 'RAL 1027',
        color: '#A38C15',
    },
    {
        id: '24',
        colorCategoryId: '2',
        name: 'Дынно-жёлтый',
        ral: 'RAL 1028',
        color: '#FFAB00',
    },
    {
        id: '25',
        colorCategoryId: '2',
        name: 'Жёлтый ракитник',
        ral: 'RAL 1032',
        color: '#DDB20F',
    },
    {
        id: '26',
        colorCategoryId: '2',
        name: 'Георгиново-жёлтый',
        ral: 'RAL 1033',
        color: '#FAAB21',
    },
    {
        id: '27',
        colorCategoryId: '2',
        name: 'Пастельно-жёлтый',
        ral: 'RAL 1034',
        color: '#EDAB56',
    },
    {
        id: '31',
        colorCategoryId: '3',
        name: 'Жёлто-оранжевый',
        ral: 'RAL 2000',
        color: '#DD7907',
    },
    {
        id: '32',
        colorCategoryId: '3',
        name: 'Красно-оранжевый',
        ral: 'RAL 2001',
        color: '#BE4E24',
    },
    {
        id: '33',
        colorCategoryId: '3',
        name: 'Алый',
        ral: 'RAL 2002',
        color: '#C63927',
    },
    {
        id: '34',
        colorCategoryId: '3',
        name: 'Пастельно-оранжевый',
        ral: 'RAL 2003',
        color: '#FA842B',
    },
    {
        id: '35',
        colorCategoryId: '3',
        name: 'Оранжевый',
        ral: 'RAL 2004',
        color: '#E75B12',
    },
    {
        id: '38',
        colorCategoryId: '3',
        name: 'Ярко-красно-оранжевый',
        ral: 'RAL 2008',
        color: '#F3752C',
    },
    {
        id: '39',
        colorCategoryId: '3',
        name: 'Транспортный оранжевый',
        ral: 'RAL 2009',
        color: '#E15501',
    },
    {
        id: '40',
        colorCategoryId: '3',
        name: 'Сигнальный оранжевый',
        ral: 'RAL 2010',
        color: '#D4652F',
    },
    {
        id: '41',
        colorCategoryId: '3',
        name: 'Насыщенный оранжевый',
        ral: 'RAL 2011',
        color: '#EC7C25',
    },
    {
        id: '42',
        colorCategoryId: '3',
        name: 'Лососёво-оранжевый',
        ral: 'RAL 2012',
        color: '#DB6A50',
    },
    {
        id: '44',
        colorCategoryId: '4',
        name: 'Огненно-красный',
        ral: 'RAL 3000',
        color: '#AB2524',
    },
    {
        id: '45',
        colorCategoryId: '4',
        name: 'Сигнальный красный',
        ral: 'RAL 3001',
        color: '#A02128',
    },
    {
        id: '46',
        colorCategoryId: '4',
        name: 'Карминно-красный',
        ral: 'RAL 3002',
        color: '#A1232B',
    },
    {
        id: '47',
        colorCategoryId: '4',
        name: 'Рубиново-красный',
        ral: 'RAL 3003',
        color: '#8D1D2C',
    },
    {
        id: '48',
        colorCategoryId: '4',
        name: 'Пурпурно-красный',
        ral: 'RAL 3004',
        color: '#701F29',
    },
    {
        id: '49',
        colorCategoryId: '4',
        name: 'Винно-красный',
        ral: 'RAL 3005',
        color: '#5E2028',
    },
    {
        id: '50',
        colorCategoryId: '4',
        name: 'Чёрно-красный',
        ral: 'RAL 3007',
        color: '#402225',
    },
    {
        id: '51',
        colorCategoryId: '4',
        name: 'Оксид красный',
        ral: 'RAL 3009',
        color: '#703731',
    },
    {
        id: '52',
        colorCategoryId: '4',
        name: 'Коричнево-красный',
        ral: 'RAL 3011',
        color: '#7E292C',
    },
    {
        id: '53',
        colorCategoryId: '4',
        name: 'Бежево-красный',
        ral: 'RAL 3012',
        color: '#CB8D73',
    },
    {
        id: '54',
        colorCategoryId: '4',
        name: 'Томатно-красный',
        ral: 'RAL 3013',
        color: '#9C322E',
    },
    {
        id: '55',
        colorCategoryId: '4',
        name: 'Розовый антик',
        ral: 'RAL 3014',
        color: '#D47479',
    },
    {
        id: '56',
        colorCategoryId: '4',
        name: 'Светло-розовый',
        ral: 'RAL 3015',
        color: '#E1A6AD',
    },
    {
        id: '57',
        colorCategoryId: '4',
        name: 'Кораллово-красный',
        ral: 'RAL 3016',
        color: '#AC4034',
    },
    {
        id: '58',
        colorCategoryId: '4',
        name: 'Розовый',
        ral: 'RAL 3017',
        color: '#D3545F',
    },
    {
        id: '59',
        colorCategoryId: '4',
        name: 'Клубнично-красный',
        ral: 'RAL 3018',
        color: '#D14152',
    },
    {
        id: '60',
        colorCategoryId: '4',
        name: 'Транспортный красный',
        ral: 'RAL 3020',
        color: '#C1121C',
    },
    {
        id: '61',
        colorCategoryId: '4',
        name: 'Лососёво-красный',
        ral: 'RAL 3022',
        color: '#D56D56',
    },
    {
        id: '64',
        colorCategoryId: '4',
        name: 'Малиново-красный',
        ral: 'RAL 3027',
        color: '#B42041',
    },
    {
        id: '66',
        colorCategoryId: '4',
        name: 'Ориент красный',
        ral: 'RAL 3031',
        color: '#AC323B',
    },
    {
        id: '69',
        colorCategoryId: '5',
        name: 'Красно-сиреневый',
        ral: 'RAL 4001',
        color: '#8A5A83',
    },
    {
        id: '70',
        colorCategoryId: '5',
        name: 'Красно-фиолетовый',
        ral: 'RAL 4002',
        color: '#933D50',
    },
    {
        id: '71',
        colorCategoryId: '5',
        name: 'Вересково-фиолетовый',
        ral: 'RAL 4003',
        color: '#D15B8F',
    },
    {
        id: '72',
        colorCategoryId: '5',
        name: 'Бордово-фиолетовый',
        ral: 'RAL 4004',
        color: '#691639',
    },
    {
        id: '73',
        colorCategoryId: '5',
        name: 'Сине-сиреневый',
        ral: 'RAL 4005',
        color: '#83639D',
    },
    {
        id: '74',
        colorCategoryId: '5',
        name: 'Транспортный пурпурный',
        ral: 'RAL 4006',
        color: '#992572',
    },
    {
        id: '75',
        colorCategoryId: '5',
        name: 'Пурпурно-фиолетовый',
        ral: 'RAL 4007',
        color: '#4A203B',
    },
    {
        id: '76',
        colorCategoryId: '5',
        name: 'Сигнальный фиолетовый',
        ral: 'RAL 4008',
        color: '#904684',
    },
    {
        id: '77',
        colorCategoryId: '5',
        name: 'Пастельно-фиолетовый',
        ral: 'RAL 4009',
        color: '#A38995',
    },
    {
        id: '78',
        colorCategoryId: '5',
        name: 'Телемагента',
        ral: 'RAL 4010',
        color: '#C63678',
    },
    {
        id: '81',
        colorCategoryId: '6',
        name: 'Фиолетово-синий',
        ral: 'RAL 5000',
        color: '#384C70',
    },
    {
        id: '82',
        colorCategoryId: '6',
        name: 'Зелёно-синий',
        ral: 'RAL 5001',
        color: '#1F4764',
    },
    {
        id: '83',
        colorCategoryId: '6',
        name: 'Ультрамариново-синий',
        ral: 'RAL 5002',
        color: '#2B2C7C',
    },
    {
        id: '84',
        colorCategoryId: '6',
        name: 'Сапфирово-синий',
        ral: 'RAL 5003',
        color: '#2A3756',
    },
    {
        id: '85',
        colorCategoryId: '6',
        name: 'Чёрно-синий',
        ral: 'RAL 5004',
        color: '#1D1F2A',
    },
    {
        id: '86',
        colorCategoryId: '6',
        name: 'Сигнальный синий',
        ral: 'RAL 5005',
        color: '#154889',
    },
    {
        id: '87',
        colorCategoryId: '6',
        name: 'Бриллиантово-синий',
        ral: 'RAL 5007',
        color: '#41678D',
    },
    {
        id: '88',
        colorCategoryId: '6',
        name: 'Серо-синий',
        ral: 'RAL 5008',
        color: '#313C48',
    },
    {
        id: '89',
        colorCategoryId: '6',
        name: 'Лазурно-синий',
        ral: 'RAL 5009',
        color: '#2E5978',
    },
    {
        id: '90',
        colorCategoryId: '6',
        name: 'Горечавково-синий',
        ral: 'RAL 5010',
        color: '#13447C',
    },
    {
        id: '91',
        colorCategoryId: '6',
        name: 'Стально-синий',
        ral: 'RAL 5011',
        color: '#232C3F',
    },
    {
        id: '92',
        colorCategoryId: '6',
        name: 'Голубой',
        ral: 'RAL 5012',
        color: '#3481B8',
    },
    {
        id: '93',
        colorCategoryId: '6',
        name: 'Кобальтово-синий',
        ral: 'RAL 5013',
        color: '#232D53',
    },
    {
        id: '94',
        colorCategoryId: '6',
        name: 'Голубино-синий',
        ral: 'RAL 5014',
        color: '#6C7C98',
    },
    {
        id: '95',
        colorCategoryId: '6',
        name: 'Небесно-синий',
        ral: 'RAL 5015',
        color: '#2874B2',
    },
    {
        id: '96',
        colorCategoryId: '6',
        name: 'Транспортный синий',
        ral: 'RAL 5017',
        color: '#0E518D',
    },
    {
        id: '97',
        colorCategoryId: '6',
        name: 'Бирюзово-синий',
        ral: 'RAL 5018',
        color: '#21888F',
    },
    {
        id: '98',
        colorCategoryId: '6',
        name: 'Капри синий',
        ral: 'RAL 5019',
        color: '#1A5784',
    },
    {
        id: '99',
        colorCategoryId: '6',
        name: 'Океанская синь',
        ral: 'RAL 5020',
        color: '#0B4151',
    },
    {
        id: '100',
        colorCategoryId: '6',
        name: 'Водная синь',
        ral: 'RAL 5021',
        color: '#07737A',
    },
    {
        id: '101',
        colorCategoryId: '6',
        name: 'Ночной синий',
        ral: 'RAL 5022',
        color: '#2F2A5A',
    },
    {
        id: '102',
        colorCategoryId: '6',
        name: 'Отдалённо-синий',
        ral: 'RAL 5023',
        color: '#4D668E',
    },
    {
        id: '103',
        colorCategoryId: '6',
        name: 'Пастельно-синий',
        ral: 'RAL 5024',
        color: '#6A93B0',
    },
    {
        id: '106',
        colorCategoryId: '7',
        name: 'Патиново-зелёный',
        ral: 'RAL 6000',
        color: '#327662',
    },
    {
        id: '107',
        colorCategoryId: '7',
        name: 'Изумрудно-зелёный',
        ral: 'RAL 6001',
        color: '#28713E',
    },
    {
        id: '108',
        colorCategoryId: '7',
        name: 'Лиственно-зелёный',
        ral: 'RAL 6002',
        color: '#276235',
    },
    {
        id: '109',
        colorCategoryId: '7',
        name: 'Оливково-зелёный',
        ral: 'RAL 6003',
        color: '#4B573E',
    },
    {
        id: '110',
        colorCategoryId: '7',
        name: 'Сине-зелёный',
        ral: 'RAL 6004',
        color: '#0E4243',
    },
    {
        id: '111',
        colorCategoryId: '7',
        name: 'Зелёный мох',
        ral: 'RAL 6005',
        color: '#0F4336',
    },
    {
        id: '112',
        colorCategoryId: '7',
        name: 'Серо-оливковый',
        ral: 'RAL 6006',
        color: '#40433B',
    },
    {
        id: '113',
        colorCategoryId: '7',
        name: 'Бутылочно-зелёный',
        ral: 'RAL 6007',
        color: '#283424',
    },
    {
        id: '114',
        colorCategoryId: '7',
        name: 'Коричнево-зелёный',
        ral: 'RAL 6008',
        color: '#35382E',
    },
    {
        id: '115',
        colorCategoryId: '7',
        name: 'Пихтовый зелёный',
        ral: 'RAL 6009',
        color: '#26392F',
    },
    {
        id: '116',
        colorCategoryId: '7',
        name: 'Травяной зелёный',
        ral: 'RAL 6010',
        color: '#3E753B',
    },
    {
        id: '117',
        colorCategoryId: '7',
        name: 'Резедово-зелёный',
        ral: 'RAL 6011',
        color: '#66825B',
    },
    {
        id: '118',
        colorCategoryId: '7',
        name: 'Чёрно-зелёный',
        ral: 'RAL 6012',
        color: '#31403D',
    },
    {
        id: '119',
        colorCategoryId: '7',
        name: 'Тростниково-зелёный',
        ral: 'RAL 6013',
        color: '#797C5A',
    },
    {
        id: '120',
        colorCategoryId: '7',
        name: 'Жёлто-оливковый',
        ral: 'RAL 6014',
        color: '#444337',
    },
    {
        id: '121',
        colorCategoryId: '7',
        name: 'Чёрно-оливковый',
        ral: 'RAL 6015',
        color: '#3D403A',
    },
    {
        id: '122',
        colorCategoryId: '7',
        name: 'Бирюзово-зелёный',
        ral: 'RAL 6016',
        color: '#026A52',
    },
    {
        id: '123',
        colorCategoryId: '7',
        name: 'Майский зелёный',
        ral: 'RAL 6017',
        color: '#468641',
    },
    {
        id: '124',
        colorCategoryId: '7',
        name: 'Желто-зелёный',
        ral: 'RAL 6018',
        color: '#48A43F',
    },
    {
        id: '125',
        colorCategoryId: '7',
        name: 'Бело-зелёный',
        ral: 'RAL 6019',
        color: '#B7D9B1',
    },
    {
        id: '126',
        colorCategoryId: '7',
        name: 'Хромовый зелёный',
        ral: 'RAL 6020',
        color: '#354733',
    },
    {
        id: '127',
        colorCategoryId: '7',
        name: 'Бледно-зелёный',
        ral: 'RAL 6021',
        color: '#86A47C',
    },
    {
        id: '128',
        colorCategoryId: '7',
        name: 'Коричнево-оливковый',
        ral: 'RAL 6022',
        color: '#3E3C32',
    },
    {
        id: '129',
        colorCategoryId: '7',
        name: 'Транспортный зелёный',
        ral: 'RAL 6024',
        color: '#008754',
    },
    {
        id: '130',
        colorCategoryId: '7',
        name: 'Папоротниково-зелёный',
        ral: 'RAL 6025',
        color: '#53753C',
    },
    {
        id: '131',
        colorCategoryId: '7',
        name: 'Опаловый зелёный',
        ral: 'RAL 6026',
        color: '#005D52',
    },
    {
        id: '132',
        colorCategoryId: '7',
        name: 'Светло-зелёный',
        ral: 'RAL 6027',
        color: '#81C0BB',
    },
    {
        id: '133',
        colorCategoryId: '7',
        name: 'Сосновый зелёный',
        ral: 'RAL 6028',
        color: '#2D5546',
    },
    {
        id: '134',
        colorCategoryId: '7',
        name: 'Мятно-зелёный',
        ral: 'RAL 6029',
        color: '#007243',
    },
    {
        id: '135',
        colorCategoryId: '7',
        name: 'Сигнальный зелёный',
        ral: 'RAL 6032',
        color: '#0F8558',
    },
    {
        id: '136',
        colorCategoryId: '7',
        name: 'Мятно-бирюзовый',
        ral: 'RAL 6033',
        color: '#478A84',
    },
    {
        id: '137',
        colorCategoryId: '7',
        name: 'Пастельно-бирюзовый',
        ral: 'RAL 6034',
        color: '#7FB0B2',
    },
    {
        id: '142',
        colorCategoryId: '8',
        name: 'Серая белка',
        ral: 'RAL 7000',
        color: '#7E8B92',
    },
    {
        id: '143',
        colorCategoryId: '8',
        name: 'Серебристо-серый',
        ral: 'RAL 7001',
        color: '#8F999F',
    },
    {
        id: '144',
        colorCategoryId: '8',
        name: 'Оливково-серый',
        ral: 'RAL 7002',
        color: '#817F68',
    },
    {
        id: '145',
        colorCategoryId: '8',
        name: 'Серый мох',
        ral: 'RAL 7003',
        color: '#7A7B6D',
    },
    {
        id: '146',
        colorCategoryId: '8',
        name: 'Сигнальный серый',
        ral: 'RAL 7004',
        color: '#9EA0A1',
    },
    {
        id: '147',
        colorCategoryId: '8',
        name: 'Мышино-серый',
        ral: 'RAL 7005',
        color: '#6B716F',
    },
    {
        id: '148',
        colorCategoryId: '8',
        name: 'Бежево-серый',
        ral: 'RAL 7006',
        color: '#756F61',
    },
    {
        id: '149',
        colorCategoryId: '8',
        name: 'Серое хаки',
        ral: 'RAL 7008',
        color: '#746643',
    },
    {
        id: '150',
        colorCategoryId: '8',
        name: 'Зелёно-серый',
        ral: 'RAL 7009',
        color: '#5B6259',
    },
    {
        id: '151',
        colorCategoryId: '8',
        name: 'Брезентово-серый',
        ral: 'RAL 7010',
        color: '#575D57',
    },
    {
        id: '152',
        colorCategoryId: '8',
        name: 'Железно-серый',
        ral: 'RAL 7011',
        color: '#555D61',
    },
    {
        id: '153',
        colorCategoryId: '8',
        name: 'Базальтово-серый',
        ral: 'RAL 7012',
        color: '#596163',
    },
    {
        id: '154',
        colorCategoryId: '8',
        name: 'Коричнево-серый',
        ral: 'RAL 7013',
        color: '#555548',
    },
    {
        id: '155',
        colorCategoryId: '8',
        name: 'Сланцево-серый',
        ral: 'RAL 7015',
        color: '#51565C',
    },
    {
        id: '156',
        colorCategoryId: '8',
        name: 'Антрацитово-серый',
        ral: 'RAL 7016',
        color: '#373F43',
    },
    {
        id: '157',
        colorCategoryId: '8',
        name: 'Чёрно-серый',
        ral: 'RAL 7021',
        color: '#2E3234',
    },
    {
        id: '158',
        colorCategoryId: '8',
        name: 'Серая умбра',
        ral: 'RAL 7022',
        color: '#4B4D46',
    },
    {
        id: '159',
        colorCategoryId: '8',
        name: 'Серый бетон',
        ral: 'RAL 7023',
        color: '#818479',
    },
    {
        id: '160',
        colorCategoryId: '8',
        name: 'Графитовый серый',
        ral: 'RAL 7024',
        color: '#474A50',
    },
    {
        id: '161',
        colorCategoryId: '8',
        name: 'Гранитовый серый',
        ral: 'RAL 7026',
        color: '#374447',
    },
    {
        id: '162',
        colorCategoryId: '8',
        name: 'Каменно-серый',
        ral: 'RAL 7030',
        color: '#939388',
    },
    {
        id: '163',
        colorCategoryId: '8',
        name: 'Сине-серый',
        ral: 'RAL 7031',
        color: '#5D6970',
    },
    {
        id: '164',
        colorCategoryId: '8',
        name: 'Галечный серый',
        ral: 'RAL 7032',
        color: '#B9B9A8',
    },
    {
        id: '165',
        colorCategoryId: '8',
        name: 'Цементно-серый',
        ral: 'RAL 7033',
        color: '#818979',
    },
    {
        id: '166',
        colorCategoryId: '8',
        name: 'Жёлто-серый',
        ral: 'RAL 7034',
        color: '#939176',
    },
    {
        id: '167',
        colorCategoryId: '8',
        name: 'Светло-серый',
        ral: 'RAL 7035',
        color: '#CBD0CC',
    },
    {
        id: '168',
        colorCategoryId: '8',
        name: 'Платиново-серый',
        ral: 'RAL 7036',
        color: '#9A9697',
    },
    {
        id: '169',
        colorCategoryId: '8',
        name: 'Пыльно-серый',
        ral: 'RAL 7037',
        color: '#7C7F7E',
    },
    {
        id: '170',
        colorCategoryId: '8',
        name: 'Агатовый серый',
        ral: 'RAL 7038',
        color: '#B4B8B0',
    },
    {
        id: '171',
        colorCategoryId: '8',
        name: 'Кварцевый серый',
        ral: 'RAL 7039',
        color: '#6B695F',
    },
    {
        id: '172',
        colorCategoryId: '8',
        name: 'Серое окно',
        ral: 'RAL 7040',
        color: '#9DA3A6',
    },
    {
        id: '173',
        colorCategoryId: '8',
        name: 'Транспортный серый A',
        ral: 'RAL 7042',
        color: '#8F9695',
    },
    {
        id: '174',
        colorCategoryId: '8',
        name: 'Транспортный серый B',
        ral: 'RAL 7043',
        color: '#4E5451',
    },
    {
        id: '175',
        colorCategoryId: '8',
        name: 'Серый шёлк',
        ral: 'RAL 7044',
        color: '#BDBDB2',
    },
    {
        id: '176',
        colorCategoryId: '8',
        name: 'Телегрей 1',
        ral: 'RAL 7045',
        color: '#91969A',
    },
    {
        id: '177',
        colorCategoryId: '8',
        name: 'Телегрей 2',
        ral: 'RAL 7046',
        color: '#82898E',
    },
    {
        id: '178',
        colorCategoryId: '8',
        name: 'Телегрей 4',
        ral: 'RAL 7047',
        color: '#CFD0CF',
    },
    {
        id: '180',
        colorCategoryId: '9',
        name: 'Зелёно-коричневый',
        ral: 'RAL 8000',
        color: '#887142',
    },
    {
        id: '181',
        colorCategoryId: '9',
        name: 'Охра коричневая',
        ral: 'RAL 8001',
        color: '#9C6B30',
    },
    {
        id: '182',
        colorCategoryId: '9',
        name: 'Сигнальный коричневый',
        ral: 'RAL 8002',
        color: '#7B5141',
    },
    {
        id: '183',
        colorCategoryId: '9',
        name: 'Глиняный коричневый',
        ral: 'RAL 8003',
        color: '#80542F',
    },
    {
        id: '184',
        colorCategoryId: '9',
        name: 'Медно-коричневый',
        ral: 'RAL 8004',
        color: '#8F4E35',
    },
    {
        id: '185',
        colorCategoryId: '9',
        name: 'Олень коричневый',
        ral: 'RAL 8007',
        color: '#6F4A2F',
    },
    {
        id: '186',
        colorCategoryId: '9',
        name: 'Оливково-коричневый',
        ral: 'RAL 8008',
        color: '#6F4F28',
    },
    {
        id: '187',
        colorCategoryId: '9',
        name: 'Орехово-коричневый',
        ral: 'RAL 8011',
        color: '#5A3A29',
    },
    {
        id: '188',
        colorCategoryId: '9',
        name: 'Красно-коричневый',
        ral: 'RAL 8012',
        color: '#673831',
    },
    {
        id: '189',
        colorCategoryId: '9',
        name: 'Сепия коричневый',
        ral: 'RAL 8014',
        color: '#49392D',
    },
    {
        id: '190',
        colorCategoryId: '9',
        name: 'Каштаново-коричневый',
        ral: 'RAL 8015',
        color: '#633A34',
    },
    {
        id: '191',
        colorCategoryId: '9',
        name: 'Махагон коричневый',
        ral: 'RAL 8016',
        color: '#4C2F26',
    },
    {
        id: '192',
        colorCategoryId: '9',
        name: 'Шоколадно-коричневый',
        ral: 'RAL 8017',
        color: '#44322D',
    },
    {
        id: '193',
        colorCategoryId: '9',
        name: 'Серо-коричневый',
        ral: 'RAL 8019',
        color: '#3F3A3A',
    },
    {
        id: '194',
        colorCategoryId: '9',
        name: 'Чёрно-коричневый',
        ral: 'RAL 8022',
        color: '#211F20',
    },
    {
        id: '195',
        colorCategoryId: '9',
        name: 'Оранжево-коричневый',
        ral: 'RAL 8023',
        color: '#A65E2F',
    },
    {
        id: '196',
        colorCategoryId: '9',
        name: 'Бежево-коричневый',
        ral: 'RAL 8024',
        color: '#79553C',
    },
    {
        id: '197',
        colorCategoryId: '9',
        name: 'Бледно-коричневый',
        ral: 'RAL 8025',
        color: '#755C49',
    },
    {
        id: '198',
        colorCategoryId: '9',
        name: 'Терракотовый',
        ral: 'RAL 8028',
        color: '#4E3B2B',
    },
    {
        id: '200',
        colorCategoryId: '10',
        name: 'Кремово-белый',
        ral: 'RAL 9001',
        color: '#EFEBDC',
    },
    {
        id: '201',
        colorCategoryId: '10',
        name: 'Светло-серый',
        ral: 'RAL 9002',
        color: '#DDDED4',
    },
    {
        id: '202',
        colorCategoryId: '10',
        name: 'Сигнальный белый',
        ral: 'RAL 9003',
        color: '#F4F8F4',
    },
    {
        id: '203',
        colorCategoryId: '10',
        name: 'Сигнальный чёрный',
        ral: 'RAL 9004',
        color: '#2E3032',
    },
    {
        id: '204',
        colorCategoryId: '10',
        name: 'Чёрный янтарь',
        ral: 'RAL 9005',
        color: '#0A0A0D',
    },
    {
        id: '207',
        colorCategoryId: '10',
        name: 'Белый',
        ral: 'RAL 9010',
        color: '#F7F9EF',
    },
    {
        id: '209',
        colorCategoryId: '10',
        name: 'Транспортный белый',
        ral: 'RAL 9016',
        color: '#F7FBF5',
    },
    {
        id: '210',
        colorCategoryId: '10',
        name: 'Транспортный чёрный',
        ral: 'RAL 9017',
        color: '#2A2D2F',
    },
    {
        id: '211',
        colorCategoryId: '10',
        name: 'Папирусно-белый',
        ral: 'RAL 9018',
        color: '#CFD3CD',
    },
]

export default colors
