// @ts-nocheck

import {
    AssocListOfProductsInterface,
    OldProductInterface,
} from '../types/models/product-interface'
// import {productsBeds} from './products/products-beds'
// import {productsTables} from './products/products-tables'
// import {productsChairs} from './products/products-chairs'
// import {productsBedsideTables} from './products/products-bedside-tables'
// import {productsWardrobes} from './products/products-wardrobes'
import arrayToAssocList from '../helpers/array-to-assoc-list'

const products: OldProductInterface[] = [
    {
        id: '1',
        name: 'Афина',
        categoryId: '1',
        article: '1',
        translit: ' krovat-afina',
        cost: '6000',
        description: '',
        creationDate: '2020-05-11 14:51:16',
    },
    {
        id: '2',
        name: 'Стол-парта с рамкой',
        categoryId: '9',
        article: '2',
        translit: 'stol-parta-s-ramkoj',
        cost: '5700',
        description: '',
        creationDate: '2020-05-11 14:54:13',
    },
    {
        id: '3',
        name: 'Ваня (жест/мягк)',
        categoryId: '5',
        article: '3',
        translit: 'stul-vanya-zhest-myagk',
        cost: '2100',
        description: '',
        creationDate: '2020-05-11 14:56:48',
    },
    {
        id: '4',
        name: 'Классика',
        categoryId: '3',
        article: '',
        translit: 'tumba-klassika',
        cost: '6600',
        description: '',
        creationDate: '2020-05-11 14:59:10',
    },
    {
        id: '5',
        name: 'Шкаф-купе (2-х ств. - вешалка)',
        categoryId: '2',
        article: '6',
        translit: 'shkaf-kupe-2-h-stv-veshalka',
        cost: '17500',
        description: '',
        creationDate: '2020-05-11 15:00:56',
    },
    {
        id: '8',
        name: 'Афродита',
        categoryId: '1',
        article: null,
        translit: 'krovat-afrodita',
        cost: '6000',
        description: '',
        creationDate: '2020-05-11 18:10:26',
    },
    {
        id: '9',
        name: 'Гармония',
        categoryId: '1',
        article: null,
        translit: 'krovat-garmoniya',
        cost: '9200',
        description: '',
        creationDate: '2020-05-11 18:11:24',
    },
    {
        id: '10',
        name: 'Гера',
        categoryId: '1',
        article: null,
        translit: 'krovat-gera',
        cost: '5900',
        description: '',
        creationDate: '2020-05-11 18:12:21',
    },
    {
        id: '11',
        name: 'Дачная простая',
        categoryId: '1',
        article: null,
        translit: 'krovat-dachnaya-prostaya',
        cost: '4550',
        description: '',
        creationDate: '2020-05-11 18:12:55',
    },
    {
        id: '12',
        name: 'Дачная точеная',
        categoryId: '1',
        article: null,
        translit: 'krovat-dachnaya-tochenaya',
        cost: '4750',
        description: '',
        creationDate: '2020-05-11 18:13:32',
    },
    {
        id: '13',
        name: 'Джулия',
        categoryId: '1',
        article: null,
        translit: 'krovat-dzhuliya',
        cost: '5750',
        description: '',
        creationDate: '2020-05-11 18:14:23',
    },
    {
        id: '14',
        name: 'Диана',
        categoryId: '1',
        article: null,
        translit: 'krovat-diana',
        cost: '5550',
        description: '',
        creationDate: '2020-05-11 18:14:57',
    },
    {
        id: '15',
        name: 'Классика',
        categoryId: '1',
        article: null,
        translit: 'krovat-klassika',
        cost: '5950',
        description: '',
        creationDate: '2020-05-11 18:15:56',
    },
    {
        id: '16',
        name: 'Лагуна',
        categoryId: '1',
        article: null,
        translit: 'krovat-laguna',
        cost: '5150',
        description: '',
        creationDate: '2020-05-11 18:16:30',
    },
    {
        id: '17',
        name: 'Лама',
        categoryId: '1',
        article: null,
        translit: 'krovat-lama',
        cost: '5800',
        description: '',
        creationDate: '2020-05-11 18:17:00',
    },
    {
        id: '18',
        name: 'Лира',
        categoryId: '1',
        article: null,
        translit: 'krovat-lira',
        cost: '6300',
        description: '',
        creationDate: '2020-05-11 18:17:23',
    },
    {
        id: '19',
        name: 'Машенька',
        categoryId: '1',
        article: null,
        translit: 'mashenka',
        cost: '4950',
        description: '',
        creationDate: '2020-05-11 18:18:25',
    },
    {
        id: '20',
        name: 'Муза',
        categoryId: '1',
        article: null,
        translit: 'krovat-muza',
        cost: '5900',
        description: '',
        creationDate: '2020-05-11 18:19:05',
    },
    {
        id: '21',
        name: 'Нефертити',
        categoryId: '1',
        article: null,
        translit: 'krovat-nefertiti',
        cost: '6050',
        description: '',
        creationDate: '2020-05-11 18:19:35',
    },
    {
        id: '22',
        name: 'Нова',
        categoryId: '1',
        article: null,
        translit: 'krovat-nova',
        cost: '5750',
        description: '',
        creationDate: '2020-05-11 18:20:25',
    },
    {
        id: '23',
        name: 'Сакура',
        categoryId: '1',
        article: null,
        translit: 'krovat-sakura',
        cost: '5250',
        description: '',
        creationDate: '2020-05-11 18:20:45',
    },
    {
        id: '24',
        name: 'Сатори',
        categoryId: '1',
        article: null,
        translit: 'krovat-satori',
        cost: '5900',
        description: '',
        creationDate: '2020-05-11 18:21:17',
    },
    {
        id: '25',
        name: 'Соната',
        categoryId: '1',
        article: null,
        translit: 'krovat-sonata',
        cost: '6000',
        description: '',
        creationDate: '2020-05-11 18:21:44',
    },
    {
        id: '26',
        name: 'Сонька',
        categoryId: '1',
        article: null,
        translit: 'krovat-sonka',
        cost: '5500',
        description: '',
        creationDate: '2020-05-11 18:22:06',
    },
    {
        id: '27',
        name: 'Соня',
        categoryId: '1',
        article: null,
        translit: 'krovat-sonya',
        cost: '5350',
        description: '',
        creationDate: '2020-05-11 18:22:26',
    },
    {
        id: '28',
        name: 'Стиль',
        categoryId: '1',
        article: null,
        translit: 'krovat-stil',
        cost: '7600',
        description: '',
        creationDate: '2020-05-11 18:23:05',
    },
    {
        id: '29',
        name: 'Фараон',
        categoryId: '1',
        article: null,
        translit: 'krovat-faraon',
        cost: '8900',
        description: '',
        creationDate: '2020-05-11 18:23:42',
    },
    {
        id: '30',
        name: 'Филенка',
        categoryId: '1',
        article: null,
        translit: 'krovat-filenka',
        cost: '6000',
        description: '',
        creationDate: '2020-05-11 18:24:16',
    },
    {
        id: '31',
        name: 'Элита',
        categoryId: '1',
        article: null,
        translit: 'krovat-ehlita',
        cost: '7100',
        description: '',
        creationDate: '2020-05-11 18:25:46',
    },
    {
        id: '32',
        name: 'ЭЛИТА (кар стяжка)',
        categoryId: '1',
        article: null,
        translit: 'krovat-ehlita-kar-styazhka',
        cost: '12700',
        description: '',
        creationDate: '2020-05-11 18:26:16',
    },
    {
        id: '33',
        name: 'Юката',
        categoryId: '1',
        article: null,
        translit: 'krovat-yukata',
        cost: '6300',
        description: '',
        creationDate: '2020-05-11 18:26:53',
    },
    {
        id: '34',
        name: 'ВИОЛА (ковка+кар стяжка)',
        categoryId: '1',
        article: null,
        translit: 'krovat-viola-kovka-kar-styazhka',
        cost: '19550',
        description: '',
        creationDate: '2020-05-11 18:28:23',
    },
    {
        id: '35',
        name: 'Дачная 2-х яр. точеная',
        categoryId: '1',
        article: null,
        translit: 'krovat-dachnaya-2-h-yar-tochenaya',
        cost: '8200',
        description: '',
        creationDate: '2020-05-11 18:29:48',
    },
    {
        id: '36',
        name: 'Маша 2-х яр. №1',
        categoryId: '1',
        article: null,
        translit: 'krovat-masha-2-h-yar-1',
        cost: '9100',
        description: '',
        creationDate: '2020-05-11 18:30:21',
    },
    {
        id: '37',
        name: 'Соня 2-х яр. №2',
        categoryId: '1',
        article: null,
        translit: 'krovat-sonya-2-h-yar-2',
        cost: '9700',
        description: '',
        creationDate: '2020-05-11 18:30:57',
    },
    {
        id: '38',
        name: 'Чердак',
        categoryId: '1',
        article: null,
        translit: 'krovat-cherdak',
        cost: '8800',
        description: '',
        creationDate: '2020-05-11 18:31:35',
    },
    {
        id: '39',
        name: 'Дачная',
        categoryId: '3',
        article: null,
        translit: 'tumba-dachnaya',
        cost: '2000',
        description: '',
        creationDate: '2020-05-11 18:34:13',
    },
    {
        id: '40',
        name: 'Стиль',
        categoryId: '3',
        article: null,
        translit: 'tumba-stil',
        cost: '2800',
        description: '',
        creationDate: '2020-05-11 18:34:39',
    },
    {
        id: '41',
        name: 'Фараон',
        categoryId: '3',
        article: null,
        translit: 'tumba-faraon',
        cost: '2800',
        description: '',
        creationDate: '2020-05-11 18:35:01',
    },
    {
        id: '42',
        name: 'Новая с резьбой',
        categoryId: '3',
        article: null,
        translit: 'tumba-novaya-s-rezboj',
        cost: '2600',
        description: '',
        creationDate: '2020-05-11 18:36:02',
    },
    {
        id: '44',
        name: 'Классика (ниша)',
        categoryId: '3',
        article: null,
        translit: 'tumba-klassika-nisha',
        cost: '2200',
        description: '',
        creationDate: '2020-05-11 18:37:09',
    },
    {
        id: '45',
        name: 'Тумбочки с рис. (афина, соната, сатори, муза)',
        categoryId: '3',
        article: null,
        translit: 'tumba-tumbochki-s-ris-afina-sonata-satori-muza',
        cost: '2200',
        description: '',
        creationDate: '2020-05-11 18:38:05',
    },
    {
        id: '46',
        name: 'Филенка',
        categoryId: '3',
        article: null,
        translit: 'tumba-filenka',
        cost: '2200',
        description: '',
        creationDate: '2020-05-11 18:38:41',
    },
    {
        id: '47',
        name: 'Классика ТВ',
        categoryId: '3',
        article: null,
        translit: 'klassika-tv',
        cost: '6600',
        description: '',
        creationDate: '2020-05-11 18:39:58',
    },
    {
        id: '48',
        name: 'Сонет ТВ',
        categoryId: '3',
        article: null,
        translit: 'tumba-sonet-tv',
        cost: '6700',
        description: '',
        creationDate: '2020-05-11 18:41:05',
    },
    {
        id: '49',
        name: 'Престиж ТВ',
        categoryId: '3',
        article: null,
        translit: 'tumba-prestizh-tv',
        cost: '7000',
        description: '',
        creationDate: '2020-05-11 18:41:33',
    },
    {
        id: '50',
        name: 'Тумба для обуви малая',
        categoryId: '3',
        article: null,
        translit: 'tumba-dlya-obuvi-malaya',
        cost: '4500',
        description: '',
        creationDate: '2020-05-11 18:42:27',
    },
    {
        id: '51',
        name: 'Тумба для обуви большая',
        categoryId: '3',
        article: null,
        translit: 'tumba-dlya-obuvi-bolshaya',
        cost: '8500',
        description: '',
        creationDate: '2020-05-11 18:42:53',
    },
    {
        id: '52',
        name: 'Обувница',
        categoryId: '3',
        article: null,
        translit: 'tumba-obuvnica',
        cost: '4000',
        description: '',
        creationDate: '2020-05-11 18:44:06',
    },
    {
        id: '53',
        name: 'Пеленальный столик',
        categoryId: '3',
        article: null,
        translit: 'tumba-pelenalnyj-stolik',
        cost: '8400',
        description: '',
        creationDate: '2020-05-11 18:44:38',
    },
    {
        id: '54',
        name: 'Туалетный столик с зеркалом',
        categoryId: '3',
        article: null,
        translit: 'tumba-tualetnyj-stolik-s-zerkalom',
        cost: '12800',
        description: '',
        creationDate: '2020-05-11 18:45:33',
    },
    {
        id: '55',
        name: 'Письменный стол',
        categoryId: '3',
        article: null,
        translit: 'tumba-pismennyj-stol',
        cost: '15000',
        description: '',
        creationDate: '2020-05-11 18:46:33',
    },
    {
        id: '56',
        name: 'Вешалка д/прихожей (полка+4крючка)',
        categoryId: '3',
        article: null,
        translit: 'tumba-veshalka-d-prihozhej-polka-4kryuchka',
        cost: '3500',
        description: '',
        creationDate: '2020-05-11 18:47:44',
    },
    {
        id: '57',
        name: 'Фараон (2-х ств. - вешалка)',
        categoryId: '2',
        article: null,
        translit: 'faraon-2-h-stv-veshalka',
        cost: '16900',
        description: '',
        creationDate: '2020-05-11 18:52:15',
    },
    {
        id: '58',
        name: 'Фараон (2-х ств. - вешалка+полки)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-faraon-2-h-stv-veshalka-polki',
        cost: '20200',
        description: '',
        creationDate: '2020-05-11 18:53:06',
    },
    {
        id: '59',
        name: 'Фараон (3-х створчатый)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-faraon-3-h-stvorchatyj',
        cost: '24200',
        description: '',
        creationDate: '2020-05-11 18:54:00',
    },
    {
        id: '60',
        name: 'Фараон (4-х створчатый)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-faraon-4-h-stvorchatyj',
        cost: '31500',
        description: '',
        creationDate: '2020-05-11 18:54:51',
    },
    {
        id: '61',
        name: 'Классика (2-х ств. - вешалка)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-klassika-2-h-stv-veshalka',
        cost: '16500',
        description: '',
        creationDate: '2020-05-11 18:55:30',
    },
    {
        id: '62',
        name: 'Классика (2-х ств. - вешалка + полки)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-klassika-2-h-stv-veshalka-polki',
        cost: '19600',
        description: '',
        creationDate: '2020-05-11 18:56:15',
    },
    {
        id: '63',
        name: 'Шкаф-купе (2-х ств. - вешалка)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-shkaf-kupe-2-h-stv-veshalka',
        cost: '17500',
        description: '',
        creationDate: '2020-05-11 18:58:21',
    },
    {
        id: '64',
        name: 'Шкаф-купе (2-х ств. - вешалка + полки)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-shkaf-kupe-2-h-stv-veshalka-polki',
        cost: '20600',
        description: '',
        creationDate: '2020-05-11 18:59:01',
    },
    {
        id: '65',
        name: 'Шкаф-купе (3-х створчатый)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-shkaf-kupe-3-h-stvorchatyj',
        cost: '23800',
        description: '',
        creationDate: '2020-05-11 18:59:29',
    },
    {
        id: '66',
        name: 'Шкаф-купе (4-х створчатый)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-shkaf-kupe-4-h-stvorchatyj',
        cost: '31500',
        description: '',
        creationDate: '2020-05-11 18:59:55',
    },
    {
        id: '67',
        name: 'Афина (2-х ств. - вешалка + полки)',
        categoryId: '2',
        article: null,
        translit: 'shkaf-afina-2-h-stv-veshalka-polki',
        cost: '18300',
        description: '',
        creationDate: '2020-05-11 19:00:58',
    },
    {
        id: '68',
        name: 'Стол-парта',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-parta',
        cost: '5400',
        description: '',
        creationDate: '2020-05-11 19:04:02',
    },
    {
        id: '69',
        name: 'Стол В1 (однобал. нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-v1-odnobal-nerazdv',
        cost: '5700',
        description: '',
        creationDate: '2020-05-11 19:06:00',
    },
    {
        id: '70',
        name: 'Стол В2 (двубал. нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-v2-dvubal-nerazdv',
        cost: '6300',
        description: '',
        creationDate: '2020-05-11 19:06:43',
    },
    {
        id: '71',
        name: 'Стол В4 (точ. нож.  нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-v4-toch-nozh-nerazdv',
        cost: '6300',
        description: '',
        creationDate: '2020-05-11 19:09:31',
    },
    {
        id: '72',
        name: 'Стол №1 (нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-1-nerazdv',
        cost: '5900',
        description: '',
        creationDate: '2020-05-11 19:10:46',
    },
    {
        id: '73',
        name: 'Стол №2 (брус нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-2-brus-nerazdv',
        cost: '6300',
        description: '',
        creationDate: '2020-05-11 19:13:33',
    },
    {
        id: '74',
        name: 'Стол №3 (нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-3-nerazdv',
        cost: '5900',
        description: '',
        creationDate: '2020-05-11 19:14:53',
    },
    {
        id: '75',
        name: 'Стол-паук',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-pauk-odnobal-nerazdv',
        cost: '6200',
        description: '',
        creationDate: '2020-05-11 19:15:37',
    },
    {
        id: '76',
        name: 'Стол-паук (двубал. нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-pauk-dvubal-nerazdv',
        cost: '6800',
        description: '',
        creationDate: '2020-05-11 19:17:22',
    },
    {
        id: '77',
        name: 'Стол (дачный нераздв)',
        categoryId: '4',
        article: null,
        translit: 'stol-stol-dachnyj-nerazdv',
        cost: '5900',
        description: '',
        creationDate: '2020-05-11 19:18:11',
    },
    {
        id: '78',
        name: 'Стол журнальный однобалясный     ',
        categoryId: '8',
        article: null,
        translit: 'stol-stol-zhurnalnyj-odnobalyasnyj',
        cost: '4300',
        description: '',
        creationDate: '2020-05-11 19:19:48',
    },
    {
        id: '79',
        name: 'Стол журнальный 2-х балясный',
        categoryId: '8',
        article: null,
        translit: 'stol-stol-zhurnalnyj-2-h-balyasnyj',
        cost: '4700',
        description: '',
        creationDate: '2020-05-11 19:20:21',
    },
    {
        id: '80',
        name: 'Стол журнальный слоник',
        categoryId: '8',
        article: null,
        translit: 'stol-stol-zhurnalnyj-slonik',
        cost: '4800',
        description: '',
        creationDate: '2020-05-11 19:20:45',
    },
    {
        id: '81',
        name: 'Стол журнальный ж4',
        categoryId: '8',
        article: null,
        translit: 'stol-stol-zhurnalnyj-zh4',
        cost: '4500',
        description: '',
        creationDate: '2020-05-11 19:21:26',
    },
    {
        id: '82',
        name: 'Гранд',
        categoryId: '5',
        article: null,
        translit: 'stul-grand',
        cost: '2100',
        description: '',
        creationDate: '2020-05-11 19:26:13',
    },
    {
        id: '83',
        name: 'Стул точеный жесткий',
        categoryId: '5',
        article: null,
        translit: 'stul-stul-tochenyj-zhestkij',
        cost: '2000',
        description: '',
        creationDate: '2020-05-11 19:27:10',
    },
    {
        id: '84',
        name: 'Стул точеный полумягкий',
        categoryId: '5',
        article: null,
        translit: 'stul-stul-tochenyj-polumyagkij',
        cost: '2100',
        description: '',
        creationDate: '2020-05-11 19:27:44',
    },
    {
        id: '85',
        name: 'Лорд',
        categoryId: '5',
        article: null,
        translit: 'stul-lord',
        cost: '2100',
        description: '',
        creationDate: '2020-05-11 19:28:11',
    },
    {
        id: '86',
        name: 'Стул дачный (лак)',
        categoryId: '5',
        article: null,
        translit: 'stul-dachnyj-lak',
        cost: '2100',
        description: '',
        creationDate: '2020-05-11 19:28:49',
    },
    {
        id: '87',
        name: 'Миша',
        categoryId: '5',
        article: null,
        translit: 'stul-misha',
        cost: '2000',
        description: '',
        creationDate: '2020-05-11 19:29:38',
    },
    {
        id: '88',
        name: 'Фортуна (№1, №2, №3) береза',
        categoryId: '5',
        article: null,
        translit: 'stul-fortuna-1-2-3-bereza',
        cost: '2900',
        description: '',
        creationDate: '2020-05-11 19:30:24',
    },
    {
        id: '89',
        name: 'Банкетка',
        categoryId: '5',
        article: null,
        translit: 'stul-banketka',
        cost: '1350',
        description: '',
        creationDate: '2020-05-11 19:43:53',
    },
    {
        id: '90',
        name: 'Табурет точеный, круглый жесткий',
        categoryId: '11',
        article: null,
        translit: 'taburet-taburet-tochenyj-kruglyj-zhestkij',
        cost: '1000',
        description: '',
        creationDate: '2020-05-11 19:48:05',
    },
    {
        id: '91',
        name: 'Табурет Новый',
        categoryId: '11',
        article: null,
        translit: 'taburet-taburet-novyj',
        cost: '900',
        description: '',
        creationDate: '2020-05-11 19:48:52',
    },
    {
        id: '92',
        name: 'Табурет Дачный (лак)',
        categoryId: '11',
        article: null,
        translit: 'taburet-taburet-dachnyj-lak',
        cost: '900',
        description: '',
        creationDate: '2020-05-11 19:49:27',
    },
    {
        id: '93',
        name: 'Табурет Квадра',
        categoryId: '11',
        article: null,
        translit: 'taburet-taburet-kvadra',
        cost: '900',
        description: '',
        creationDate: '2020-05-11 19:49:56',
    },
    {
        id: '94',
        name: 'Лавка Банная',
        categoryId: '13',
        article: null,
        translit: 'lavka-bannaya',
        cost: '2500',
        description: '',
        creationDate: '2020-05-11 19:50:38',
    },
    {
        id: '95',
        name: 'Лавка (лак)',
        categoryId: '13',
        article: null,
        translit: 'stul-lavka',
        cost: '2500',
        description: '',
        creationDate: '2020-05-11 19:53:25',
    },
    {
        id: '96',
        name: 'Стиль',
        categoryId: '14',
        article: null,
        translit: 'komod-stil',
        cost: '7500',
        description: '',
        creationDate: '2020-05-11 19:58:50',
    },
    {
        id: '98',
        name: 'Фараон',
        categoryId: '14',
        article: null,
        translit: 'komod-faraon',
        cost: '7500',
        description: '',
        creationDate: '2020-05-11 19:59:54',
    },
    {
        id: '99',
        name: 'Новый',
        categoryId: '14',
        article: null,
        translit: 'komod-novyj',
        cost: '7000',
        description: '',
        creationDate: '2020-05-11 20:00:27',
    },
    {
        id: '100',
        name: 'Филенка',
        categoryId: '14',
        article: null,
        translit: 'komod-filenka',
        cost: '7000',
        description: '',
        creationDate: '2020-05-11 20:01:19',
    },
    {
        id: '101',
        name: 'Зеркало',
        categoryId: '14',
        article: null,
        translit: 'komod-zerkalo',
        cost: '4500',
        description: '',
        creationDate: '2020-05-11 20:01:43',
    },
]

// eslint-disable-next-line one-var
// const ids = new Set()
// let maxId = 0
// products.forEach((product, i) => {
//     const prevLength = ids.size
//     ids.add(product.id)
//     // Значит айдишник не уникален
//     if (ids.size === prevLength)
//         console.warn('ID продукта не уникален! ', product.id)
//     if (product.id > maxId) maxId = product.id
// })
// console.warn('Последний ID продукта ', maxId)

const assocListOfProducts: AssocListOfProductsInterface = arrayToAssocList(
    products
)

export default assocListOfProducts
