enum T {
    LOAD_PRODUCTS_STARTED = 'LOAD_PRODUCTS_STARTED',
    LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS',
    LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS',
    LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR',

    LOAD_PRODUCT_STARTED = 'LOAD_PRODUCT_STARTED',
    LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS',
    LOAD_PRODUCT_ERROR = 'LOAD_PRODUCT_ERROR',

    ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART',
    DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART',
}

export default T
